// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: mic_srv_office.proto

package go_micro_service_mic_srv_office

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MicSrvOffice service

func NewMicSrvOfficeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MicSrvOffice service

type MicSrvOfficeService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MicSrvOffice_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (MicSrvOffice_PingPongService, error)
}

type micSrvOfficeService struct {
	c    client.Client
	name string
}

func NewMicSrvOfficeService(name string, c client.Client) MicSrvOfficeService {
	return &micSrvOfficeService{
		c:    c,
		name: name,
	}
}

func (c *micSrvOfficeService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MicSrvOffice.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *micSrvOfficeService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MicSrvOffice_StreamService, error) {
	req := c.c.NewRequest(c.name, "MicSrvOffice.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &micSrvOfficeServiceStream{stream}, nil
}

type MicSrvOffice_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type micSrvOfficeServiceStream struct {
	stream client.Stream
}

func (x *micSrvOfficeServiceStream) Close() error {
	return x.stream.Close()
}

func (x *micSrvOfficeServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micSrvOfficeServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micSrvOfficeServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micSrvOfficeServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *micSrvOfficeService) PingPong(ctx context.Context, opts ...client.CallOption) (MicSrvOffice_PingPongService, error) {
	req := c.c.NewRequest(c.name, "MicSrvOffice.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &micSrvOfficeServicePingPong{stream}, nil
}

type MicSrvOffice_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type micSrvOfficeServicePingPong struct {
	stream client.Stream
}

func (x *micSrvOfficeServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *micSrvOfficeServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *micSrvOfficeServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micSrvOfficeServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micSrvOfficeServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *micSrvOfficeServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MicSrvOffice service

type MicSrvOfficeHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, MicSrvOffice_StreamStream) error
	PingPong(context.Context, MicSrvOffice_PingPongStream) error
}

func RegisterMicSrvOfficeHandler(s server.Server, hdlr MicSrvOfficeHandler, opts ...server.HandlerOption) error {
	type micSrvOffice interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type MicSrvOffice struct {
		micSrvOffice
	}
	h := &micSrvOfficeHandler{hdlr}
	return s.Handle(s.NewHandler(&MicSrvOffice{h}, opts...))
}

type micSrvOfficeHandler struct {
	MicSrvOfficeHandler
}

func (h *micSrvOfficeHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MicSrvOfficeHandler.Call(ctx, in, out)
}

func (h *micSrvOfficeHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicSrvOfficeHandler.Stream(ctx, m, &micSrvOfficeStreamStream{stream})
}

type MicSrvOffice_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type micSrvOfficeStreamStream struct {
	stream server.Stream
}

func (x *micSrvOfficeStreamStream) Close() error {
	return x.stream.Close()
}

func (x *micSrvOfficeStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micSrvOfficeStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micSrvOfficeStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micSrvOfficeStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *micSrvOfficeHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MicSrvOfficeHandler.PingPong(ctx, &micSrvOfficePingPongStream{stream})
}

type MicSrvOffice_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type micSrvOfficePingPongStream struct {
	stream server.Stream
}

func (x *micSrvOfficePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *micSrvOfficePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micSrvOfficePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micSrvOfficePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micSrvOfficePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *micSrvOfficePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
